# Generated by Django 4.1.13 on 2025-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date when employee was hired', null=True, verbose_name='Hire Date'),
        ),
    ]
